# Generated by Django 5.2 on 2025-04-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='bot_reply',
            new_name='bot_response',
        ),
    ]
